language: swift
osx_image: xcode10

branches:
 only:
 - master

script:
 - xcodebuild build -project AirAware.xcodeproj -scheme AirAware -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' | xcpretty

